services:
  Mvo\ContaoGroupWidget\Group\Registry:
    arguments:
      - '@Psr\Container\ContainerInterface'

  Mvo\ContaoGroupWidget\EventListener\GroupWidgetListener:
    arguments:
      - '@request_stack'
      - '@Mvo\ContaoGroupWidget\Group\Registry'
