services:
  Mvo\ContaoGroupWidget\Group\Registry:
    arguments:
      - '@twig'
      - '@database_connection'

  Mvo\ContaoGroupWidget\EventListener\GroupWidgetListener:
    arguments:
      - '@request_stack'
      - '@Mvo\ContaoGroupWidget\Group\Registry'
